version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      #checking version
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 993471916179.dkr.ecr.us-east-1.amazonaws.com
      - # Replace with this to your repository URI
      - REPOSITORY_URI=993471916179.dkr.ecr.us-east-1.amazonaws.com/project-ahr-repo
    build:
    commands:
      - echo Build started on `date`
      - echo building the Jar file
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
  post_build:
    commands:
artifacts:
  files:
    - target/MyApplication.jar